/*
 * This file is generated by jOOQ.
 */
package com.example.demo;


import com.example.demo.tables.Route;
import com.example.demo.tables.Ticket;
import com.example.demo.tables.Train;
import com.example.demo.tables.Trip;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.route</code>.
     */
    public final Route ROUTE = Route.ROUTE;

    /**
     * The table <code>public.ticket</code>.
     */
    public final Ticket TICKET = Ticket.TICKET;

    /**
     * The table <code>public.train</code>.
     */
    public final Train TRAIN = Train.TRAIN;

    /**
     * The table <code>public.trip</code>.
     */
    public final Trip TRIP = Trip.TRIP;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Route.ROUTE,
            Ticket.TICKET,
            Train.TRAIN,
            Trip.TRIP
        );
    }
}
