/*
 * This file is generated by jOOQ.
 */
package com.example.demo;


import com.example.demo.tables.Route;
import com.example.demo.tables.Ticket;
import com.example.demo.tables.Train;
import com.example.demo.tables.Trip;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.route</code>.
     */
    public static final Route ROUTE = Route.ROUTE;

    /**
     * The table <code>public.ticket</code>.
     */
    public static final Ticket TICKET = Ticket.TICKET;

    /**
     * The table <code>public.train</code>.
     */
    public static final Train TRAIN = Train.TRAIN;

    /**
     * The table <code>public.trip</code>.
     */
    public static final Trip TRIP = Trip.TRIP;
}
