/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.records;


import com.example.demo.tables.Train;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainRecord extends UpdatableRecordImpl<TrainRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.train.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.train.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.train.model</code>.
     */
    public void setModel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.train.model</code>.
     */
    public String getModel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.train.passenger_capacity</code>.
     */
    public void setPassengerCapacity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.train.passenger_capacity</code>.
     */
    public Integer getPassengerCapacity() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Train.TRAIN.ID;
    }

    @Override
    public Field<String> field2() {
        return Train.TRAIN.MODEL;
    }

    @Override
    public Field<Integer> field3() {
        return Train.TRAIN.PASSENGER_CAPACITY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getModel();
    }

    @Override
    public Integer component3() {
        return getPassengerCapacity();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getModel();
    }

    @Override
    public Integer value3() {
        return getPassengerCapacity();
    }

    @Override
    public TrainRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TrainRecord value2(String value) {
        setModel(value);
        return this;
    }

    @Override
    public TrainRecord value3(Integer value) {
        setPassengerCapacity(value);
        return this;
    }

    @Override
    public TrainRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrainRecord
     */
    public TrainRecord() {
        super(Train.TRAIN);
    }

    /**
     * Create a detached, initialised TrainRecord
     */
    public TrainRecord(Integer id, String model, Integer passengerCapacity) {
        super(Train.TRAIN);

        setId(id);
        setModel(model);
        setPassengerCapacity(passengerCapacity);
        resetChangedOnNotNull();
    }
}
